### ISSUE TITLE
Unable to import amplitude tag

### ISSUE THREAD

**Issue by headler** [amplitude/amplitude-gtm-template#2]
Hello,
After applying recent update to template, start receiving an error in console:
`Error parsing 'integrity' attribute ('sha384-VuGgAcmMrGHihvjXxxBVMIqoDFXc8/PO9q/08kCgq4Wn1iPnSmUbI3xhXaFozVFv"'). The digest must be a valid, base64-encoded value.`
What might be the reason?

Thank you

**Comment by dnshi** [comment]
Hey @headler , thanks for reporting the issue. I have committed a fix for the issue and published a new release. The new release should be available shortly.
